name: Auto Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          echo "Starting deployment..."

          # Navigate to project directory
          cd /home/deploy/telegram-gym-bot || exit 1

          # Pull latest code
          echo "Pulling latest code from GitHub..."
          git pull origin main || exit 1

          # Make scripts executable
          chmod +x scripts/deploy.sh

          # Run deployment script
          echo "Running deployment script..."
          ./scripts/deploy.sh

          echo "Deployment completed!"